### ISSUE TITLE
not working in chrome

### ISSUE THREAD

**Issue by Faruque5698** [brian2694/laravel-toastr#12]

**Comment by brian2694** [comment]
Could you give me more information?

Laravel version, package version, chrome version and specifically what is not working.

Thanks.

**Comment by brian2694** [comment]
Hi Faruque5698, we have waited for 45 days without receiving a response from you. Therefore, we are going to close this issue due to inactivity. If you have more information or need further assistance with this problem in the future, please don't hesitate to open a new issue. Thank you for your interest in our project.
